@startuml Structures of Entities
class Category{
    int Id
    string Name 

    List<UserCategory> UserCategories
    List<TestCategory> TestCategories
}
class Test{
    int Id
    string Name
    int Score
    
    List<Question> Questions
    List<TestCategory> TestCategories
}
class Question{
    int Id
    string Text
    int Points

    Answere Answer
    int TestId
    Test Test
}
class Answer{
    int Id
    string Text

    int QuestionId
    Question Question
}
class User{
    int Id
    string Name

    List<UserCategory> UserCategories
}

class UserCategory{
    int UserId
    User User

    int CategoryId
    Category Category
}

class TestCategory{
    int TestId
    Test Test

    int CategoryId
    Category Category
}
User o-- UserCategory
Category o-- UserCategory
Category  o-- TestCategory
Test o-- TestCategory
Test o-- Question
Question <-- Answer
@enduml